In [1]:
# Import all necessary libraries.
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix

In [2]:
# Select just a few of these categories, and download the training and testing set.
# Features.
x_train = np.array(['Chinese Beijing Chinese', 'Chinese Chinese Shanghai','Chinese Macao',
'Tokyo Japan Chinese'])

# Features.
y_train = np.array(['china','china','china','not china'])

# Test Features.
x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

# Bernoulli NB

In [3]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer(binary=True)

# Fit and transform X_train into X_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print('Vetor com o nome dos atributos')
print(vect.get_feature_names())
print('\nMatriz de contagem dos atributos')
print(x_train_dtm.toarray())

# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)
print('\n Vector de contagem')
print(x_test_dtm.toarray())


# Instantiate a Bernoulli Naive Bayes model.
model = BernoulliNB(binarize=None)

# Train the BernoulliNB model X_train_dtm.
model.fit(x_train_dtm, y_train)

Vetor com o nome dos atributos
['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']

Matriz de contagem dos atributos
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]

 Vector de contagem
[[0 1 1 0 0 1]]


BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [4]:
y_pred_class = model.predict(x_test_dtm)
print('Conforme a predição, a mensagem - "Chinese Chinese Chinese Tokyo Japan" pertence a classe: ', y_pred_class)
print('\n Probabilidades da predição:')
print(model.predict_proba(x_test_dtm))

Conforme a predição, a mensagem - "Chinese Chinese Chinese Tokyo Japan" pertence a classe:  ['not china']

 Probabilidades da predição:
[[0.19106679 0.80893321]]


***7D. Como você deve ter percebido, existe diferença na classificação feita pelos 2 classificadores. Explique o motivo da classificação feita por cada classificador.***
R: A distribuição de Bernoulli considera que os atributos são variáveis binárias ou seja, o atributo pode estar presente ou ausente. Usa os atributos binários da ocorrência de termos.

# Multinomial NB

In [5]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer(binary=False)

# Fit and transform X_train into X_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

print('Vetor com o nome dos atributos')
print(vect.get_feature_names())
print('\nMatriz de contagem dos atributos')
print(x_train_dtm.toarray())

# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)
print('\n Vector de contagem')
print(x_test_dtm.toarray())

# Instantiate a Multinomial Naive Bayes model.
model = MultinomialNB()

# Train the MultinomialNB model X_train_dtm.
model.fit(x_train_dtm, y_train)

Vetor com o nome dos atributos
['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']

Matriz de contagem dos atributos
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]

 Vector de contagem
[[0 3 1 0 0 1]]


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [6]:
y_pred_class = model.predict(x_test_dtm)
print('Conforme a predição, a mensagem - "Chinese Chinese Chinese Tokyo Japan" pertence a classe: ',y_pred_class)

print('\n Probabilidades da predição:')
print(model.predict_proba(x_test_dtm))

Conforme a predição, a mensagem - "Chinese Chinese Chinese Tokyo Japan" pertence a classe:  ['china']

 Probabilidades da predição:
[[0.68975861 0.31024139]]


***7D. Como você deve ter percebido, existe diferença na classificação feita pelos 2 classificadores. Explique o motivo da classificação feita por cada classificador.***
R: A distribuição multinomial descreve a probabilidade de observar contagens entre várias categorias ou seja realiza a contagem das frequências de termos. Onde atributos são discretos e representam as frequências.